services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1002
      POSTGRES_DB: coopah_test
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: my_redis
    ports:
      - "6379:6379"
