services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5437:5432"
    env_file:
      - test.env

  redis:
    image: redis:7
    container_name: my_redis
    ports:
      - "6379:6379"
    env_file:
      - test.env
