name: Coopah CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Create test environment file
        run: |
          echo "DB_HOST=my_postgres" >> test.env
          echo "DB_USER=postgres" >> test.env
          echo "DB_PORT=5437" >> test.env
          echo "DB_NAME=testdb" >> test.env
          echo "APP_SECRET=secret" >> test.env
          echo "PORT=7482" >> test.env
          echo "DB_PASSWORD=3333" >> test.env
          echo "JWT_EXPIRES_SECONDS=368883" >> test.env
          echo "REDIS_URL=redis://localhost:6379" >> test.env

      - name: Run tests
        run: make test
