name: Coopah CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Start Docker services
        run: docker compose -f docker-compose.test.yaml up -d

      - name: Run tests
        run: make run-tests
